### ISSUE TITLE
run.sh Permission denied

### ISSUE THREAD

**Issue by Zerho-213** [oliverde8/Dockerfiles#1]
Hi i have use your dockerfile, after the all instalation, on lunch the docker-compose, on the line "Cheking for database update" i have this "bin/run.sh: line 12: ./bin/console: Permission denied" i don't understand why. And next, the docker closes. Can you help my pls ?

**Comment by oliverde8** [comment]
First of all the docker isn't uptodate 👎 to me I forgot that. 🤔 I thought our release tool triggered it at the end. I will check that. 

 I will test the docker and comeback to see why that error happened.

**Comment by oliverde8** [comment]
Thanks for reporting the issue, it has been fixed. 👍
